const path = require('path');
const express = require('express');
const { v4: uuidv4 } = require('uuid');
const utils = require('../libs/utils');
const upload = require('../libs/multer');
const { runImitator, zipImitatorFiles } = require('../libs/imitator');

const router = express.Router();

/* GET home page. */
router.get('/', (req, res) => {
  res.render('index');
});

/* POST imitator run. */
router.post('/run', upload, async (req, res) => {
  try {
    // @ts-ignore
    const models = req.files.models;

    // @ts-ignore
    const property = req.files.property[0];

    // @ts-ignore
    const timeout = req.body.timeout;

    // identifier of the run
    const identifier = uuidv4();
    const outputFolder = path.join(property.destination, identifier);

    const propertyPath = await utils.moveToFolder(outputFolder, [property]);
    const modelsPath = await utils.moveToFolder(outputFolder, models);

    // imitator options
    let options = req.body.options || '';
    options = options.length !== 0 ? options.trim().split(' ') : [];

    // filter options
    const forbiddenOptions = ['-output-prefix'];
    options = options.filter((o) => {
      const sentOption = o.split('=')[0];
      return !forbiddenOptions.includes(sentOption);
    });

    // run all the experiments asynchronously
    const outputs = await Promise.all(
      modelsPath.map((m) =>
        runImitator(m, propertyPath[0], options, timeout, outputFolder)
      )
    );

    // zip all the files generated by imitator
    const zipFile = await zipImitatorFiles(outputs, outputFolder);

    const result = {
      options,
      identifier,
      outputs,
      file: zipFile,
      models: models.map((m) => m.originalname),
      property: property.originalname,
    };

    res.render('result', { result });
  } catch (error) {
    res.render('error', {
      message: 'Oops',
      error: { status: 500, stack: error },
    });
  }
});

module.exports = router;
