const fs = require('fs');
const path = require('path');
const cron = require('node-cron');
const config = require('../config');

/**
# ┌──────────── minute (0 - 59)
# │ ┌────────── hour (0 - 23)
# │ │ ┌──────── day of month (1 - 31)
# │ │ │ ┌────── month (1 - 12)
# │ │ │ │ ┌──── day of week (0 - 6)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
*/

/**
 * Remove all the files in a directory
 *
 * @param {string} directory directory where the files are stored
 */
async function removeFilesInDirectory(directory) {
  const files = await fs.promises.readdir(directory);

  Promise.all(files.map((f) => fs.promises.unlink(path.join(directory, f))));
}

/**
 * Clean temporary files generated by imitator (every day)
 */
const cleanScheduler = cron.schedule('0 0 * * *', async () => {
  const directory = config.uploadFolder;
  console.log(
    `[cronjob] cleaning temporary imitator files in ${directory} ...`
  );
  await removeFilesInDirectory(directory);
});

/**
 * Start all the cronjobs
 */
function initialize() {
  cleanScheduler.start();
}

module.exports = initialize;
